---
title: "proj3"
author: "Jingtian Yao"
date: "March 14, 2018"
output: html_document
---

## Construct RGB Features

```{r}
library(readr)
library(ggplot2)
library(caret)
library(Matrix)
library(xgboost)

set.seed(1)
source("../lib/featureRGB.R")

img_dir <- "../data/train/train/"

time_ftr <- system.time(rgb_feature <- featureRGB(img_dir,export = T))

cat("Time for constructing RGB features is",time_ftr[3],"s \n")

labeldata <- read.csv("../data/train/train/label_train.csv")
rgb_feature$label <- labeldata$label

trainimg <- sample(1:3000,2100)
testimg <- setdiff(1:3000,trainimg)
train.rgb <- rgb_feature[trainimg,]
test.rgb <- rgb_feature[testimg,]

write.csv(train.rgb,file = "../output/rgbftr_train.csv")

write.csv(test.rgb,file = "../output/rgbftr_test.csv")

write.csv(rgb_feature, file = "../output/rgbftr.csv")

#train.rgb <- read.csv("../output/rgbftr_train.csv")
#train.rgb <- train.rgb[,-1]
#test.rgb <- read.csv("../output/rgbftr_test.csv")
#test.rgb <- test.rgb[,-1]
```

## XGboost based on RGB features

```{r}
source("../lib/xgb.R")
time_cv <- system.time(cv_rgb <- xgb_param(train.rgb,5))
cat("Time for selecting best parameters is",time_cv[3],"s \n")

param <- cv_rgb$best_param

#param <- list(eta = 0.15, max_depth = 4)
time_model <- system.time(model <- xgb_model(train.rgb,param))
cat("Time for building xgboost model is",time_model[3],"s \n")

time_pred <- system.time(pred <- xgb_pred(model, test.rgb))
cat("Time for predicting test data is",time_pred[3],"s \n")

imp <- xgb.importance(feature_names = colnames(train.rgb),model = model)

imp_col <- head(imp$Feature)
imp_col <- as.numeric(gsub("X","",imp_col))
Bimp <- (imp_col%/%120)+1
Gimp <- ((imp_col%%120)%/%10)+1
Rimp <- (imp_col%%120)%%10

col <- NULL
for(i in 1:length(imp_col)){
  temp <- rgb(Rimp[i]*12-6,Gimp[i]*10-5,Bimp[i]*10-5,maxColorValue = 120)
  col <- c(col,temp)
}

col # important colors

pred$err
```


## Xgboost based on SIFT features

```{r}
sift_feature <- read.csv("../data/train/train/SIFT_train.csv",header = F)
sift_feature$label <- labeldata$label
sift_feature <- sift_feature[,-1]

train.sift <- sift_feature[trainimg,]
test.sift <- sift_feature[testimg,]

model2 <- xgb_model(train.sift,param)
pred2 <- xgb_pred(model2, test.sift)
pred2$err

```


